# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7904-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter m20lte a40,$(TARGET_DEVICE)),)

endif
